### PR TITLE
Update xlsw.py: fix timedelta support

### PR DESCRIPTION
**Pull request by vinraspa**
fix timedelta support

With your PR, here is a check list:

- [ ] Has test cases written?
- [ ] Has all code lines tested?
- [ ] Has `make format` been run?
- [ ] Please update CHANGELOG.yml(not CHANGELOG.rst)
- [ ] Has fair amount of documentation if your change is complex
- [ ] Agree on NEW BSD License for your contribution

### CODE REVIEW

**Comment by chfw** [comment]
I am happy that you fix the problem. But does it make sense to support timedelta? So can you describe your use case?

**Comment by vinraspa** [comment]
I write a python program that must export ical events to a spreadsheet.
Events have a begin and end times (`datetime`) and duration (`timedelta`) fields.
I want user to be able to play with these fields (sum, min, max, ...)

Currently, with pyexcel module:
 * `xlsx` format supports both `datetime` and `timedelta` (this is cool and this proves it's possible)
 * `xls` format supports `datime` but not `timedelta`
 * `ods` format supports `timedelta` but not `datetime`
That is why I made PRs to pyexcel-xls, pyexcel-ods3 and pyexcel-io projects.

**Comment by chfw** [comment]
I see. But xlrd returns date time for timedelta. How do you translate it back to date time?

**Comment by vinraspa** [comment]
Yes, this is an issue
The conversion works only one way (python->xls) but not the other.
It would require `xlrd` deal differently when time **format** contains `[H]` or `[HH]` (instead of anything else).
I will think about it a bit. 

Is it worth it? maybe you are right. After all, xls format is less and less used.

**Comment by chfw** [comment]
Xls has a limit on the number of rows so it is better to avoid using xls. UK’s national health service used xls format to persist collected reported COVID cases in 2020 and got a mystery problem: where did the data go? Oh well, xls skipped excessive rows.

**Comment by chfw** [comment]
I think we can release the change but note it in doc. Of course, If you are able to work out the remedying solution, and it can be added to the doc.

**Comment by vinraspa** [comment]
By 'the doc', do you mean 'README.rst'?

**Pull request merged**
